### ISSUE TITLE
v0.9.5 does not work with Erlang OTP 26 on Windows 10

### ISSUE THREAD

**Issue by fuributas** [pgourlain/vscode_erlang#268] opened 2023-07-05 06:52 UTC
Hi,

This is my environment:
- Windows 10 Pro 22H2
- Clean portable installacion of VSCode-win32-x64-1.79.2
- vscode_erlang v0.9.5
- Erlang OTP 26.0.2

When I open an Erlang file, it seems that the extension hangs on 'rebar3 compile':

![image](https://github.com/pgourlain/vscode_erlang/assets/15906053/0b579a91-3bd8-4329-848f-cd260d9e5882)

But if I switch to Erlang OTP 25.2.3.2 it works seamless.

Thanks.

**Comment by pgourlain** [comment] 2024-05-29 05:02
Hi

Do you have same problem with newest version ?

**Comment by MinhDuc-Tran** [comment] 2024-07-18 04:19
Hi,
I face the similar problem on Ubuntu with latest version v1.0.9.
It works with OTP v25. but not for OTP v26.

OTP v25
> erlang extension is active
> using erlang binaries from path : '.../OTP-25.3.2.7-statssl/bin'
> starting : escript 
> ...
> escript exit code:0 

OTP v26
> erlang extension is active
> starting : escript 
> .../.vscode-server/extensions/pgourlain.erlang-1.0.9/rebar3 compile
> /bin/sh: 1: escript: not found
> escript exit code:127

Kindly help check.

**Comment by pgourlain** [comment] 2024-07-18 05:53
hi,

what is your configuration for erlang path.
<img width="547" alt="image" src="https://github.com/user-attachments/assets/0d82f852-36a2-47cd-9e03-e231d3109cab">

it seems that escript is not in the environment path.
can you check in your sh shell 'whereis escript' 
do you have restarted vscode after OTP26 installation ?

**Comment by pgourlain** [comment] 2024-10-26 05:55
Hi,

since July, I didn't reproduce this .

I close this ticket, open a new one if you repeat this.

**Closed by pgourlain** 2024-10-26 05:55 UTC
